import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import { loadConfig } from "../config/load.ts";
import { BookError } from "../errors.ts";

export const WORKFLOW_PATH = ".github/workflows/md2book-pages.yml";
/** Where the workflow builds the site, relative to the book folder (`<out>/web/`). */
const OUT = "dist/pages";

export interface GithubPagesOptions {
  /** Book config path. */
  config: string;
  /** Replace an existing workflow. */
  force?: boolean;
}

export interface WorkflowSettings {
  /** md2book version the workflow installs. */
  version: string;
  /** The book folder relative to the repository root (`.` at the root), `/`-separated. */
  bookDir: string;
  /** The config file name inside the book folder. */
  configFile: string;
  /** The book's own `web_url`; without it the workflow uses the URL GitHub Pages reports. */
  webUrl?: string;
}

/**
 * The GitHub Actions workflow: build the web edition with md2book and deploy it to GitHub Pages.
 * It runs only when started by hand (Actions tab), so nothing is deployed until the author does.
 */
export function pagesWorkflow(settings: WorkflowSettings): string {
  const { version, bookDir, configFile, webUrl } = settings;
  const site = bookDir === "." ? `${OUT}/web` : `${bookDir}/${OUT}/web`;
  // Pages reports the site's URL: https://<owner>.github.io/<repo> for a project site, or the
  // custom domain set in the repository's Pages settings.
  const urlFlag = webUrl ? "" : ' --web-url "${{ steps.pages.outputs.base_url }}/"';
  return `# Generated by md2book ${version} (md2book deploy github-pages).
# Builds the web edition of the book and deploys it to GitHub Pages.
# Before the first run: Settings → Pages → Build and deployment → Source: GitHub Actions.
# Site URL: ${webUrl ? `web_url in ${configFile} (${webUrl})` : "the URL GitHub Pages reports (set web_url for a fixed one)"}.
name: Deploy web edition to GitHub Pages

on:
  # Deploys only when started from the Actions tab. To deploy on every push, add:
  # push:
  #   branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: md2book-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${JSON.stringify(bookDir)}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
      - id: pages
        uses: actions/configure-pages@v5
      - name: Install md2book and Chromium
        run: |
          npm install -g @thixpin/md2book@${version}
          node "$(npm root -g)/@thixpin/md2book/node_modules/playwright/cli.js" install --with-deps chromium
      - name: Fetch the fonts
        run: md2book fonts --config ${JSON.stringify(configFile)}
      - name: Build the web edition
        run: md2book build web --config ${JSON.stringify(configFile)} --out ${OUT}${urlFlag}
      - uses: actions/upload-pages-artifact@v5
        with:
          path: ${JSON.stringify(site)}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
`;
}

/** The nearest folder at or above `dir` holding `.git`, or null. */
function repositoryRoot(dir: string): string | null {
  for (let current = dir; ; current = dirname(current)) {
    if (existsSync(join(current, ".git"))) return current;
    if (dirname(current) === current) return null;
  }
}

/** `md2book deploy github-pages`: writes the workflow into the book's git repository. */
export async function runGithubPages(
  options: GithubPagesOptions,
  version: string,
): Promise<{ file: string; webUrl?: string }> {
  const configPath = resolve(options.config);
  const { config } = await loadConfig(configPath);
  const root = repositoryRoot(dirname(configPath));
  if (!root) {
    throw new BookError(
      options.config,
      "not inside a git repository; run git init and add a GitHub remote first",
    );
  }
  const file = join(root, WORKFLOW_PATH);
  if (existsSync(file) && !options.force) {
    throw new BookError(file, "already exists; use --force to replace it");
  }
  const webUrl = config.web_url || undefined;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(
    file,
    pagesWorkflow({
      version,
      bookDir: relative(root, dirname(configPath)).split(sep).join("/") || ".",
      configFile: basename(configPath),
      webUrl,
    }),
  );
  return { file, webUrl };
}
